version: "3"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      QUEUE_NAME: cola_fibonacci
      RESULT_TTL_SECONDS: "3600"
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: docker/worker.Dockerfile
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      QUEUE_NAME: cola_fibonacci
      RESULT_TTL_SECONDS: "3600"
    depends_on:
      - redis

